"""training plans

Revision ID: d7f015b7a734
Revises: b025c53a0879
Create Date: 2025-05-06 11:56:34.289993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7f015b7a734"
down_revision: Union[str, None] = "b025c53a0879"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("descriptions", sa.String(length=150), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "training_plan_clients",
        sa.Column("training_plan_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["training_plan_id"], ["training_plans.id"], ondelete="CASCADE"
        ),
    )
    op.create_table(
        "training_plan_exercises",
        sa.Column("training_plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SQUATS", "PUSH_UPS", "RUNNING", name="exercisetype"),
            nullable=False,
        ),
        sa.Column("approaches_number", sa.Integer(), nullable=False),
        sa.Column("repetitions_number", sa.Integer(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("rest_between_approaches", sa.Interval(), nullable=False),
        sa.CheckConstraint(
            "rest_between_approaches > interval '0'", name="check_rest_positive"
        ),
        sa.CheckConstraint("approaches_number > 0", name="check_approaches_positive"),
        sa.CheckConstraint("repetitions_number > 0", name="check_repetitions_positive"),
        sa.ForeignKeyConstraint(
            ["training_plan_id"], ["training_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("training_plan_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_plan_exercises")
    op.drop_table("training_plan_clients")
    op.drop_table("training_plans")
    # ### end Alembic commands ###
